services:
  ollama-service:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
        - ~/ollama_data:/root/.ollama
  qdrant-service:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
